<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="" />
    <meta name="referrer" content="origin" />
    <meta name="title" content="">
    <meta name="keywords" content="">
    <meta property="og:site_name" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title></title>
</head>

<body>
    <?php require 'partials/_header.phtml'?>
    <?php 
        if($template === "homepage"){
            require 'homepage/homepage.phtml';
        }
        else if ($template === "login"){
            require 'login/login.phtml';
        }
        else if($template === "register"){
            require 'register/register.phtml';
        }
        else if($template === "account"){
            require 'account/account.phtml';
        }
    ?>
    
    <?php require 'partials/_footer.phtml'?>
    <script type="module" src="assets/js/index.js"></script>
</body>

</html>