<form action="../../index.php" method="POST">
    <fieldset>
        <label>Prenom</label>
        <input type="text" name="firstName">
    </fieldset>
    <fieldset>
        <label>Nom</label>
        <input type="text" name="lastName">
    </fieldset>
    <fieldset>
        <label>Email</label>
        <input type="email" name="email">
    </fieldset>
    <fieldset>
        <label>Password</label>
        <input type="password" name="password">
    </fieldset>
    <fieldset>
        <label>Confirmer Password</label>
        <input type="password" name="confirm-password">
    </fieldset>
        <input type="hidden" name="formName">
    <input type="submit" name="registerSubmit" value="S'inscrire">
</form>